Update check title and remove icon
dorny/test-reporter pull request #144
Opened 2021-10-11 12:40 UTC by ldaneliukas

It would seem that the ❌ icon is somewhat redundant in most scenarios that we've seen so far. If we look at the whole workflow run, then with or without `fail-on-error` we will still always see a red cross next to the check. This is also true for the checks visible in the Pull Request itself - we already have a ❌ from Github itself. There doesn't seem to be a reason to duplicate this icon with an additional one in the title of the check.

In order to make this a little more useful, I'd propose displaying the total number of tests that succeeded, failed, and were skipped in the title instead. This helps us see a short summary of what happened in the pull request checks section and removes the ❌ icon duplication.

### Workflow summary
Before:
![image](https://user-images.githubusercontent.com/10710427/136791991-a6b884c4-c9e7-4fba-9af2-230880e6826a.png)
![image](https://user-images.githubusercontent.com/10710427/136791340-b6e8fcbe-d3b7-4c18-a2e5-fcffbd746a03.png)

### Pull  request
Before:
![image](https://user-images.githubusercontent.com/10710427/136792161-d1a0427e-e5ff-4886-a1e8-0e787860f89a.png)
After:
![image](https://user-images.githubusercontent.com/10710427/136792515-031405a3-f070-4576-8e13-828b2f742402.png)

2021-11-29 11:13 UTC, phjardas commented on src/main.ts
> +    let shortSummary = `${passed} passed, ${failed} failed and ${skipped} skipped `
This could be `const`.

2021-12-14 09:17 UTC, tdabasinskas commented
@dorny, is the project still alive?

2022-02-22 12:09 UTC, IanMoroney commented
@LDaneliukas , @phjardas , @tdabasinskas , I ran into a similar issue as yourselves where there were features that I needed from this project and looked like it wasn't being updated any time soon, so I took the initiative to fork the project myself and build the enhancements into it with a colleague.
I have also now taken this PR and added the contents into that repo so you can use them :)

https://github.com/phoenix-actions/test-reporting/
https://github.com/marketplace/actions/test-reporting

2023-02-13 19:10 UTC, karmops approved these changes
looks good

2023-09-22 19:38 UTC, j-catania approved these changes

2023-09-22 19:39 UTC, j-catania requested changes
could you please revert your dist files please

2024-01-12 09:01 UTC, j-catania approved these changes

2024-01-12 09:01 UTC, merged