add gh action output for `url` and `url_html`
dorny/test-reporter pull request #198
Opened 2022-10-04 16:57 UTC by peterwhitesell

# Changes
- [x] add github action output for `url` and `url_html` so they can be referenced by other actions in a workflow

2022-11-05 09:10 UTC, dorny commented
@peterwhitesell Thanks for your contribution.
Could you merge the current `main` to your branch and solve the conflicts?
I will merge it afterward.

2022-11-13 10:12 UTC, dorny requested changes

2022-11-13 10:12 UTC, dorny commented on src/main.ts
> +    core.setOutput('url_html', resp.data.html_url)
@peterwhitesell I've just noticed this is executed in a loop. Multiple check runs might be created if the input path has a pattern matching more files. In that case, the `url` variable would be set to the last one. What's your use case? We could leave it as is or output JSON encoded array instead. Not sure what's a better approach.

2022-11-13 10:12 UTC, dorny commented on src/main.ts
> +        return new GoJunitParser(options)
We should have go-junit support documented in the README and action.yml

2023-01-24 10:37 UTC, sonomirco commented
Hi @dorny and @peterwhitesell
This is precisely what I am looking for! 
I noticed the HTML  <github repo project>/runs/<random number>
Could this directory be fixed? So I can link it to a GitHub Env in a GitHub action doing something like this.

    environment:
      name: unit-test
      url: <report-url>

2023-03-06 23:38 UTC, sonomirco commented
@peterwhitesell and @dorny seems this PR is not moving forward.
Do you have any updates?

2023-03-27 22:16 UTC, luisito666 commented
Hi i am the original developer of this PR, i plan to resend this today

2023-03-27 22:45 UTC, luisito666 commented
I am the original developer of this feature and i decide to create another PR
Here is the PR https://github.com/dorny/test-reporter/pull/242

2024-01-12 09:11 UTC, j-catania commented
#242 Merged.
Thanks both

2024-01-12 09:11 UTC, closed without merging