Support for the PHPUnit dialect of JUnit
dorny/test-reporter pull request #422
Opened 2024-04-09 17:58 UTC by mbeccati

PHPUnit uses nested `<testsuite>` elements, and the actual test cases are ignored in the current version of the reporter.

This is my first attempt at TypeScript, so apologies for any silly mistake.

Most likely it would be best to implement it as a separate parser, add more features, such as better error reporting, file links, etc.

As a first prototype, it seems to be working good enough for my current needs, e.g. https://github.com/mbeccati/php-latest-builds/runs/23625536886

2024-04-10 13:10 UTC, darshanrampatel commented
@mbeccati An interesting approach - when I needed to do this, I instead modified the PHPUnit test file to match the JUnit format:

```
# Change from
#
# <testsuites>
#   <testsuite name="" ...
#   ...
#   </testsuite>
# </testsuites>
#
# to
#
# <testsuites name=""
# ...
# </testsuites>
```

I think your approach is probably better though 🙂

One thing that I'm not sure "just works" in your version is the file annotations - I had to perform some regex to get this to work. See this: https://github.com/darshanrampatel/test-reporter/blob/e8fa95a4ce020faeb9a198f9b31bf4e6e200c2b9/src/parsers/phpunit-junit/phpunit-junit-parser.ts#L182-L196

(I apologise that it's not documented😅)

2024-04-10 13:16 UTC, mbeccati commented
@darshanrampatel nice! Feel free to borrow from this PR for your fork. That would indeed make for a better PR than this one. If you do, pls let me know. Id'be more than happy to give it a try

2024-06-26 11:39 UTC, jozefizso commented
This should be a new parser specific for PHPUnit format.

2024-06-26 12:33 UTC, mbeccati commented
@jozefizso I agree. I just wasn't sure exacty where to start with a new parser, or at least that's what I recall. It's bee a while ;-)

Are you suggesting I edit the PR creating a new parser? If so I think I'd need some guidance

2025-04-04 14:18 UTC, pierrelemee commented
Faced the same issue so I tested with your changes and it [works like a charm](https://github.com/betagouv/mon-indemnisation-justice/actions/runs/14267250988/job/39992128543) ✅ (best approval I can give)

2025-05-17 14:06 UTC, jozefizso requested changes

2025-05-17 14:06 UTC, jozefizso commented on src/parsers/java-junit/java-junit-types.ts
This should be a new parser for PHPUnit format.

2025-12-29 12:23 UTC, jozefizso commented
Review findings (from code review):

- **High:** PHPUnit emits absolute paths, but the parser only accepts exact matches against `trackedFiles` (repo‑relative from `git ls-files`). This likely prevents annotations from ever resolving (`path`/`line` stay undefined). Consider mapping to repo‑relative via `getBasePath` (like `JestJunitParser`) or matching by basename. Ref: `src/parsers/phpunit-junit/phpunit-junit-parser.ts:136`, `src/parsers/phpunit-junit/phpunit-junit-parser.ts:146`.
- **Medium:** Failure details are dropped when `<failure>` is parsed as a plain string (no attributes). `details` becomes `''`, which also blocks file/line extraction from the stack trace. Add a fallback like `typeof failure === 'string' ? failure : failure._`. Ref: `src/parsers/phpunit-junit/phpunit-junit-parser.ts:129`.
- **Medium:** The stack trace regex only matches `*.php` and ignores `.phpt` and Windows drive paths, so those traces won’t be parsed even if relative mapping is added. Consider broadening the pattern. Ref: `src/parsers/phpunit-junit/phpunit-junit-parser.ts:171`.
- **Low:** README doesn’t list `phpunit-junit` in supported frameworks or in the reporter options, so the new parser isn’t discoverable. Ref: `README.md:15`, `README.md:141`.

2025-12-29 13:59 UTC, merged

2025-12-30 20:17 UTC, mbeccati commented
Brilliant, thanks!